resolve 04
Bukasik/react-fundamentals pull request #9
Opened 2020-10-08 06:18 UTC by Bukasik

2020-10-08 07:31 UTC, pvpshoot requested changes

2020-10-08 07:31 UTC, pvpshoot commented on src/exercise/04.html
> +        {message({children: 'Hello World'})}
сейчас ты в функцию объект передаешь, нужно просо строку
`<div>{message('Hello World')}</div>`

2020-10-11 05:30 UTC, Bukasik commented on src/exercise/04.html
> +        {message({children: 'Hello World'})}
поправил

2020-10-12 07:40 UTC, pvpshoot approved these changes
👍

2020-10-19 16:33 UTC, merged